# -*- coding: utf-8 -*-
"""EDA_Week01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uxZEMI29rhd6N-ZhEe9TR2YUnL2GBLVs

01 NumPy program to create an array of all even integers from 30 to 70.
"""

import numpy as np
#creating array of even integers from 30 to 70
evenArray = np.arange(30,71,2)
print(evenArray)

"""02 NumPy program to generate an array of 15 random numbers from a standard normal
distribution.

"""

import numpy as np
#creating array of 15 random numbers from SND
randomArray = np.random.randn(15)
print(randomArray)

"""03 Compute the cross-product of two matrices in NumPy"""

import numpy as np
matrix1 = np.array([2,3,4])
matrix2 = np.array([7,8,9])
#computing cross-product
crossProductResult = np.cross(matrix1, matrix2)
print(crossProductResult)

"""04 Compute the determinant of an array using NumPy

"""

import numpy as np
matrixs = np.array([[2,3,4], [5,6,7], [8,9,1]])
#calculting determinant
determinant = np.linalg.det(matrixs)
print(determinant)

"""05 Create a 3x3x3 array with random values using NumPy"""

import numpy as np
#creating 3x3x3 array with random values
randomArray = np.random.rand(3, 3, 3)
print(randomArray)

"""06 Create a 5x5 array with random values and find the minimum and maximum values using
NumPy
"""

import numpy as np
#creating 5x5 array with random values
randomArray = np.random.rand(5,5)
#finding min value
minValue = np.min(randomArray)
#finding max value
maxValue = np.max(randomArray)
print("Random array:", randomArray)
print("Minimum value:", minValue)
print("Maximum value:", maxValue)

"""07 Compute the mean, standard deviation, and variance of a given array along the second axis in
NumPy

"""

import numpy as np
#creating 2D array
array2d = np.array([[2,3,4],[5,6,7],[8,9,1]])
#computing mean along second axis
meanValue = np.mean(array2d, axis=1)
#computing standard deviation along the second axis
standardDeviationValue = np.std(array2d, axis=1)
#compute variance along the second axis
varianceValue = np.var(array2d, axis=1)
print("Original 2D Array:")
print(array2d)
print("Mean along second axis:")
print(meanValue)
print("Standard Deviation along second axis:")
print(standardDeviationValue)
print("Variance along second axis:")
print(varianceValue)